vich_uploader:
  db_driver: orm

  mappings:
    lesson_image:
      uri_prefix: /images/lessons
      upload_destination: '%kernel.project_dir%/public/images/lessons'
      namer: Vich\UploaderBundle\Naming\UniqidNamer